Update projects.md
dralabeing/uccross.github.io pull request #1
Opened 2021-11-30 00:24 UTC by dralabeing

Create a Place holder for OpenROAD projects

2021-11-30 20:01 UTC, carlosmalt commented
Thank you so much for adding your projects, @dralabeing! 

What are your plans for getting those updates into the uccross repository once we reviewed them here?

2021-11-30 20:12 UTC, dralabeing commented
Thanks @carlosmalt ..Just completed those updates. They are ready to be merged. Would you like me to merge these or will you do that? (for admin purposes)

2021-11-30 20:20 UTC, carlosmalt requested changes
Just finished my review.

2021-11-30 20:20 UTC, carlosmalt commented on projects.md
> +
Please remove this. The table of content is generated automatically.

2021-11-30 20:20 UTC, carlosmalt commented on projects.md
> +### OpenROAD - A Complete, Autonomous RTL-GDSII Flow for VLSI Designs
Based on the table of contents entries above you are leading one project (OpenROAD) for which you are offering eight project ideas. Projects are listed on section level 2 (`## OpenROAD`) and project ideas are listed on section level 3 (e.g. `### Static RAM Generator for OpenROAD-flow-scripts`).

2021-11-30 20:20 UTC, carlosmalt commented on projects.md
> +##[ OpenROAD](https://github.com/The-OpenROAD-Project) is a DARPA supported initiative through the IDEA program, that delivers an open sourced ecosystem of a complete and autonomous VLSI design flow
Remove the `##`.

2021-11-30 20:20 UTC, carlosmalt commented on projects.md
> +
Feel free to add the rest of the project ideas as level 3 sections.

2021-11-30 20:20 UTC, carlosmalt commented on projects.md
> +  * **Mentor**: Mehdi Saligane Matt Liberty
Add `mailto:` links to mentors (separated by commas).

2021-11-30 20:20 UTC, carlosmalt commented on projects.md
> +  * **Mentor**: Mehdi Saligane/Ming-Hung
Add mailto: links to mentors (separated by commas).

2021-11-30 20:21 UTC, carlosmalt commented on projects.md
> +### OpenROAD - A Complete, Autonomous RTL-GDSII Flow for VLSI Designs
Also, please try to keep level 2 section titles short.

2021-11-30 20:33 UTC, carlosmalt commented
> Thanks @carlosmalt ..Just completed those updates. They are ready to be merged. Would you like me to merge these or will you do that? (for admin purposes)

Once you opened a PR at the uccross repository, I can then merge them.

2021-12-01 02:04 UTC, carlosmalt approved these changes
This looks good -- Thanks!

2021-12-01 02:11 UTC, carlosmalt commented
Feel free to push to the origin repository (using a new branch), create a pull request, and I will then integrate your changes with other updates in the mainline.

2022-02-16 01:00 UTC, merged